source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include? '/'
  "https://github.com/#{repo_name}.git"
end

ruby '2.6.5'

gem 'bcrypt'
gem 'bootsnap', require: false
gem 'puma', '~> 3.12'
gem 'rack-cors', '>= 2.0.0', require: 'rack/cors'
gem 'rails', '~> 7.1.0.0'
gem 'sqlite3'
gem 'validate_url', '>= 1.0.10'

gem 'graphql'
gem 'graphql-query-resolver'
gem 'search_object'
gem 'search_object_graphql'

group :development, :test do
  gem 'byebug', platforms: %i(mri mingw x64_mingw)
  gem 'factory_bot_rails', '>= 5.2.0'
  gem 'graphiql-rails', '1.10.0'
  gem 'rubocop'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 4.0.2'
end
